name: Push to GCR
on:
  - push
  - workflow_dispatch

jobs:

  Build:
    name: Deploy / ${{ needs.FindEnvironment.outputs.env_name }}
    needs: FindEnvironment
    uses: ./.github/workflows/build-and-save-to-gcr.yml
    with:
      env-name: ${{ needs.FindEnvironment.outputs.env_name }}
    secrets: inherit
    
  FindEnvironment:
    name: Finding Environment
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.find_name.outputs.env_name }}
    steps:
      - id: find_name
        run: |
          if [[ ${{ github.event.ref }} == refs/heads/main ]]
          then
            echo "::set-output name=env_name::stage"
          elif [[ ${{ github.event.ref }} == refs/heads/production ]]
          then
            echo "::set-output name=env_name::prod"
          else
            echo "::set-output name=env_name::dev"
          fi    


    

