name: Push to GCR GitHub Action
on:
  - push
  - workflow_dispatch
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/push-to-gcr-github-action@v4.1
        with:
          gcloud_service_key: ${{ secrets.JSON_GCLOUD_SERVICE_ACCOUNT_JSON }} # can be base64 encoded or plain text
          registry: test-repo
          project_id: nomadic-flame-354021
          image_name: image-test
          image_tag: latest,v1
          dockerfile: ./Dockerfile

